# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestDefaultSuite():
  def setup_method(self, method):
    self.driver = webdriver.Safari()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_testLogin(self):
    self.driver.get("http://localhost:5000/login")
    self.driver.set_window_size(550, 692)
    self.driver.find_element(By.NAME, "email").click()
    self.driver.find_element(By.NAME, "email").send_keys("GG@g.com")
    self.driver.find_element(By.NAME, "password").send_keys("GG")
    self.driver.find_element(By.CSS_SELECTOR, ".btn").click()
  
